export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_TRANSACTION_CHECKED = "SET_TRANSACTION_CHECKED";
export const SET_TRANSACTION_UNCHECKED = "SET_TRANSACTION_UNCHECKED";
export const SET_REAL_SOLD = "SET_REAL_SOLD";
export const SET_FICTIVE_SOLD = "SET_FICTIVE_SOLD";

export const UPDATE_REAL_SOLD = "UPDATE_REAL_SOLD";
export const UPDATE_FICTIVE_SOLD = "UPDATE_FICTIVE_SOLD";